---
title: "Clean DivDiv Trait Data"
author: "Eric Crandall"
format: html
bibliography: test.bib
csl: nature.csl
---


@Timm_2020
@Gaither_2015
@Reich_2020, @Kitchen_2019
NA
@Reich_2020, @Kitchen_2019
@Reich_2020, @Kitchen_2019
@Bongaerts_2017
@Gonzalez_Zapata_2018
@Saenz_Agudelo_2015
@Catalano_2020
@Laporte_2015
@Laporte_2015
@Cornwell_2020
@Xuereb_2018
@Clucas_2018
@Stovall_2018
@Lavretsky_2016
@Titus_2019
@Thia_2021
@Xu_2018
NA
NA
NA
@Plough_2017
NA
@Gleason_2016
list(title = "https://www.nature.com/articles/s41559-018-0482-x", author = list(list(given = NULL, family = "Unknown", role = NULL, email = NULL, comment = NULL)), note = "A URL that didn't resolve to a DOI")
list(title = "https://scholarcommons.usf.edu/etd/7445/ AND https://data.gulfresearchinitiative.org/pelagos-symfony/data/R4.x257.000%3A0027", author = list(list(given = NULL, family = "Unknown", role = NULL, email = NULL, comment = NULL)), note = "A URL that didn't resolve to a DOI")
@Hilborn_2017, @Jansson_2020
@Salas_2019
list(title = "NA", author = list(list(given = NULL, family = "Unknown", role = NULL, email = NULL, comment = NULL)), note = "A URL that didn't resolve to a DOI")
@Chang_2018
@Le_Moan_2016
NA
NA
list(title = "https://dx.doi.org/10.1002%2Fece3.4058", author = list(list(given = NULL, family = "Unknown", role = NULL, email = NULL, comment = NULL)), note = "A URL that didn't resolve to a DOI")
@Hosoya_2019
NA
@Oziolor_2018
@Healy_2018
NA
list(title = "https://www.sciencedirect.com/science/article/pii/S0165783619300852", author = list(list(given = NULL, family = "Unknown", role = NULL, email = NULL, comment = NULL)), note = "A URL that didn't resolve to a DOI")
@Wepfer_2020
@Wepfer_2020
@Delgado_2019, @Zemlak_2010, @G_rski_2015
@Fang_2018
@Crane_2018
@Benestan_2015, @Benestan_2016
@De_Wit_2020
@Pearman_2020
@Hundt_2019
@Fern_ndez_2015
@Fern_ndez_2015
@Hodel_2018
@Zhang_2019
@Zhao_2017
NA
@Puritz_2016
@Hosoya_2019
NA
NA
@Paterno_2019
@Combosch_2017
@Collins_2018
@Leydet_2018
@Manzello_2019
list(title = "https://search.proquest.com/docview/2272213328?pq-origsite=gscholar", author = list(list(given = NULL, family = "Unknown", role = NULL, email = NULL, comment = NULL)), note = "A URL that didn't resolve to a DOI")
@Paterno_2017
NA
@Hoey_2018
@Timm_2019
@Cammen_2018
@Lah_2016
list(title = "https://www.nature.com/articles/s41598-020-71603-9", author = list(list(given = NULL, family = "Unknown", role = NULL, email = NULL, comment = NULL)), note = "A URL that didn't resolve to a DOI")
@Schiebelhut_2018
@Pfaller_2019
@Momigliano_2018
@van_Oppen_2018
@Nunez_2015
@Torquato_2019
@Dimond_2017
NA
@Clucas_2018
@Clucas_2018
@Clucas_2018
list(title = "https://scholarcommons.usf.edu/etd/7445/ AND https://data.gulfresearchinitiative.org/pelagos-symfony/data/R4.x257.000%3A0027", author = list(list(given = NULL, family = "Unknown", role = NULL, email = NULL, comment = NULL)), note = "A URL that didn't resolve to a DOI")
@Hodel_2018
list(title = "https://scholarcommons.usf.edu/etd/7445/ AND thttps://data.gulfresearchinitiative.org/pelagos-symfony/data/R4.x257.000%3A0027", author = list(list(given = NULL, family = "Unknown", role = NULL, email = NULL, comment = NULL)), note = "A URL that didn't resolve to a DOI")
@Le_Cam_2019
@Montes_2013, @2015
@Vaux_2019
@Andrews_2018
@Andrews_2018
list(title = "https://www.sciencedirect.com/science/article/pii/S1874778717300235", author = list(list(given = NULL, family = "Unknown", role = NULL, email = NULL, comment = NULL)), note = "A URL that didn't resolve to a DOI")
@Andrews_2018
@Xu_2017
@Purcell_2018
@Gould_2019
@Portnoy_2015
list(title = "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6021044/pdf/pone.0198901.pdf", author = list(list(given = NULL, family = "Unknown", role = NULL, email = NULL, comment = NULL)), note = "A URL that didn't resolve to a DOI")
list(title = "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6021044/pdf/pone.0198901.pdf", author = list(list(given = NULL, family = "Unknown", role = NULL, email = NULL, comment = NULL)), note = "A URL that didn't resolve to a DOI")
@Bongaerts_2017
NA
@Mattingsdal_2019
@Carreras_2017
@Timm_2020
@Puncher_2018
list(title = "https://academic.oup.com/gbe/article/11/7/1751/5512349", author = list(list(given = NULL, family = "Unknown", role = NULL, email = NULL, comment = NULL)), note = "A URL that didn't resolve to a DOI")
@Colston_Nepali_2019
@Colston_Nepali_2019
list(title = "https://scholarcommons.usf.edu/etd/7445/ AND https://data.gulfresearchinitiative.org/pelagos-symfony/data/R4.x257.000%3A0027", author = list(list(given = NULL, family = "Unknown", role = NULL, email = NULL, comment = NULL)), note = "A URL that didn't resolve to a DOI")
@Shafer_2016
@Bernardi_2018
@Bernardi_2018
@Hosoya_2019
