---
title: "Clean DivDiv Trait Data"
author: "Eric Crandall"
format: rtf
bibliography: test.bib
csl: nature.csl
---


@Timm_2020

@Gaither_2015

@Reich_2020, @Kitchen_2019

NA

@Reich_2020, @Kitchen_2019

@Reich_2020, @Kitchen_2019

@Bongaerts_2017

@Gonzalez_Zapata_2018

@Saenz_Agudelo_2015

@Catalano_2020

@Laporte_2015

@Laporte_2015

@Cornwell_2020

@Xuereb_2018

@Clucas_2018

@Stovall_2018

@Lavretsky_2016

@Titus_2019

@Thia_2021

@Xu_2018

NA

NA

NA

@Plough_2017

NA

@Gleason_2016

@RzBUgMsL

@Xz3rfVSU

@Hilborn_2017, @Jansson_2020

@Salas_2019

@Rv9Sy03f

@Chang_2018

@Le_Moan_2016

NA

NA

@F6TnNpb6

@Hosoya_2019

NA

@Oziolor_2018

@Healy_2018

NA

@3clrC2Sg

@Wepfer_2020

@Wepfer_2020

@Delgado_2019, @Zemlak_2010, @G_rski_2015

@Fang_2018

@Crane_2018

@Benestan_2015, @Benestan_2016

@De_Wit_2020

@Pearman_2020

@Hundt_2019

@Fern_ndez_2015

@Fern_ndez_2015

@Hodel_2018

@Zhang_2019

@Zhao_2017

NA

@Puritz_2016

@Hosoya_2019

NA

NA

@Paterno_2019

@Combosch_2017

@Collins_2018

@Leydet_2018

@Manzello_2019

@yYUVRywd

@Paterno_2017

NA

@Hoey_2018

@Timm_2019

@Cammen_2018

@Lah_2016

@WaE1EjAf

@Schiebelhut_2018

@Pfaller_2019

@Momigliano_2018

@van_Oppen_2018

@Nunez_2015

@Torquato_2019

@Dimond_2017

NA

@Clucas_2018

@Clucas_2018

@Clucas_2018

@WZjLYVl1

@Hodel_2018

@PN7Plyfs

@Le_Cam_2019

@Montes_2013, @2015

@Vaux_2019

@Andrews_2018

@Andrews_2018

@NTqUptKf

@Andrews_2018

@Xu_2017

@Purcell_2018

@Gould_2019

@Portnoy_2015

@QydPcQvv

@e35Po6Xa

@Bongaerts_2017

NA

@Mattingsdal_2019

@Carreras_2017

@Timm_2020

@Puncher_2018

@RrXUyYGm

@Colston_Nepali_2019

@Colston_Nepali_2019

@3oKa0oFc

@Shafer_2016

@Bernardi_2018

@Bernardi_2018

@Hosoya_2019

@jjonBieb

@JuvYMfMd

@Graham_2013

@Graham_2013

@Graham_2013

@Graham_2013

@Graham_2013

@Graham_2013

@bh5UJ5GF

@AV1TuVfr

@wsBYUKMM

@yQ4zDbLU

@Cornwell_2020

@Li_2011

@Kooyman_1996

@2014

@2018

@Wolfowicz_2016

@41ACS8fv

@Arellano_2014

@8luyh3m3

@EoOD0TNa

@M25u9vEA

@Macedo_2019

@AbNDaDmm

@Moran_1997

@Vq2nA8OU

@Arkhipkin_1996

@FDve7loQ

@rv5SYEq4

@2017

@Bloecher_2013

@nTTkUusd

@2020

@Grigor_2017

@g72MW0vS

@5MfDgXgE

@Q1BMrLlU

@Ramee_2016

@Scott_1954

@Churchill_2016

@dSjWb4KB

@Marquis_2005

@Baird_2009

@2s35rfsU

@CubuwnlX

@A6vUPFwD

@Annis_2007

@E1yGHLjI

@Wells_2018

@039nHOMe

@mmy0PgyV

@Galatius_2016

@2007

@10.5657/KFAS.2004.37.6.478

@M4j04SvV

@Cairns_1999

@HtkekArx

@t2ZZtR16

@WDndgbyJ

@Baird_2009

@kLuHaeoM

@Villanueva_2016

@Collins_2018

@M__2001

@Baird_2009

@Hettinger_2013

@Fenaux_1985

@bekiO62p

@inONe75C

@Timm_2021

@2016

@2020a

@Hohn_1996

@rq11AIyv

@Pfaller_2019

@jE5EiCcc

@Baird_2009

@Balon_2004

@MYBDoWhD

@Baird_2009

@Baird_2009

@Kooyman_1996

@Kooyman_1996

@Kooyman_1996

@Moreno_2008

@Guerra_Castro_2021

@Timm_2020

@Baweja_2016

@DloifVJx

@mT1W5Pu5

@eoTWDMnE

@BiWlua4J

@XNUo1Gzk

@LrhaRR2e

@fKZJdjMA

@Moran_2007

@Gould_2016

@EcXTrbke

@DYcfbVn7

@uqRTCXSS

@Baird_2009

@XVW2JeYg

@gRHEt2kq

@kSuNWyKQ

@Bartilotti_2019

@cv82uA0G

@IoOlKXxC

@LEE_2008

@4is097pw

@0EyM9ENP

@2014a

@MzzNpK8z

@VRQxJB8l

@vvGI0Yy6

@IWfqwcV6

@LljlCwvE

@Graham_2013

@Graham_2013

@Graham_2013

@Graham_2013

@Graham_2013

@Graham_2013

@UNFnGeP2

@YkDG6oVl

@ynyudfAR

@fMz0ZtbZ

@Cornwell_2020

@Li_2011

@Kooyman_1996

@2014

@2018

@Wolfowicz_2016

@TX8jI2Lq

@Arellano_2014

@LqECp0mr

@FByzvpKw

@0MzDCYeY

@Macedo_2019

@lKbYNGgW

@Moran_1997

@OYIiEpw7

@Arkhipkin_1996

@GhilkSRH

@K0kPMZ17

@2017

@Bloecher_2013

@RqtKkF6p

@2020

@Grigor_2017

@ud2uiD5k

@fxomfQvM

@FLN4VjIY

@Ramee_2016

@Scott_1954

@Churchill_2016

@q8AgutAf

@Marquis_2005

@Baird_2009

@BGt5632z

@5MqNEtip

@qvcnsSE1

@Annis_2007

@y9sjC5BK

@Wells_2018

@sDxArSsM

@H0rqMD6d

@Galatius_2016

@2007

@10.5657/KFAS.2004.37.6.478

@fN3SirQJ

@Cairns_1999

@oi7Bm4i3

@K9kqdyMQ

@I8n9YwNI

@Baird_2009

@lWJgaIT0

@Villanueva_2016

@Collins_2018

@M__2001

@Baird_2009

@Hettinger_2013

@Fenaux_1985

@cbD0tTRs

@EuH0JsSq

@Timm_2021

@2016

@2020a

@Hohn_1996

@2BbGSDuT

@Pfaller_2019

@dOA8z807

@Baird_2009

@Balon_2004

@L7ii3pJb

@Baird_2009

@Baird_2009

@Kooyman_1996

@Kooyman_1996

@Kooyman_1996

@Moreno_2008

@Guerra_Castro_2021

@Timm_2020

@Baweja_2016

@xOr6aGb5

@6riPwsjg

@AnqBSzYo

@1PPRS3yT

@yEz3hJMV

@JNxoUUgp

@3vqxTLEa

@Moran_2007

@Gould_2016

@l6chB9NQ

@oW8AJDtP

@o6Jzt91a

@Baird_2009

@r5am8qpM

@XezlVAA2

@uSLNitnm

@Bartilotti_2019

@hybZKqxa

@oFOLdHFw

@LEE_2008

@wv1EOPLI

@rzdX4zh7

@2014a

@lMu67FJF

@oSfenFdq

@lTDxKQqa

@DkoAnvwn

@SqfOtd5S

Graham, Baird, Connolly, Sewell et al. (2013)

Graham, Baird, Connolly, Sewell et al. (2013)

Graham, Baird, Connolly, Sewell et al. (2013)

Graham, Baird, Connolly, Sewell et al. (2013)

Graham, Baird, Connolly, Sewell et al. (2013)

Graham, Baird, Connolly, Sewell et al. (2013)

@1da0VLiq

@ZLzDFfAE

@e6fIZ44X

@9z6YeIQZ

Cornwell (2020)

Li, Li, Sun, and Kong (2011)

Kooyman (1996)

 (2014)

 (2018)

Wolfowicz, Baumgarten, Voss, Hambleton et al. (2016)

@esEd2Lwf

Arellano, Van Gaest, Johnson, Vrijenhoek et al. (2014)

@HfNcdLHR

@ZTIy1YwG

@l5M8MPiJ

Macedo, Caballero, Mateos, Leblois et al. (2019)

@xPZZQHIK

Moran (1997)

@iJc9o4Lv

Arkhipkin (1996)

@3CLMHTGL

@tpMmE07f

 (2017)

Bloecher, de
Nys, Poole, and Guenther (2013)

@naBL7KkB

 (2020)

Grigor, Schmid, and Fortier (2017)

@SKu777bm

@JUhypOIX

@lr5FXlsZ

Ramee and Allen (2016)

Scott (1954)

Churchill, Kritzer, Dean, Grabowski et al. (2016)

@ExaPCqw6

Marquis, Baird, de
Nys, Holmström et al. (2005)

Baird, Guest, and Willis (2009)

@IwXVWs3M

@J07cIyr0

@Qs59SUQW

Annis, Incze, Steneck, and Wolff (2007)

@6L6QGD9R

@tbZg8Szs

@K61xkG9d

Graham, Baird, Connolly, Sewell et al. (2013)

Graham, Baird, Connolly, Sewell et al. (2013)

Graham, Baird, Connolly, Sewell et al. (2013)

Graham, Baird, Connolly, Sewell et al. (2013)

Graham, Baird, Connolly, Sewell et al. (2013)

Graham, Baird, Connolly, Sewell et al. (2013)

@DVmHZwEO

@vFtEMLWa

