---
title: "DivDiv Trait Data Citations"
author: "Eric Crandall"
format: docx
bibliography: traits.bib
csl: science.csl
---



# Generational_Structure 


@Timm_2020

NA

@Madin_2016

@Madin_2016

@Madin_2016

@Madin_2016

@Madin_2016

NA

@Sebens_1981

@2020

@2014

@2018

@O_Reilly_2018

NA

@Ebert_2005

NA

NA

NA

@Gaither_2018

@Hoving_2015

NA

@Salas_2019

NA

@Fach_2014

@2020a

NA

@Grawunder_2015

NA

@edwards1992species

NA

@Madin_2016

NA

@2016

NA

NA

NA

@ongevity

@Estrada_2008

@Zhang_2019

@fishbase2000

@Madin_2016

NA

NA

@Madin_2016

@Hoving_2015

@Brandt_2009

@Hopkins_1936

@Vafidis_2019

@fishbase2000

@fishbase2000

@20range

@2020ab

@50370296

NA

NA

@fishbase2000

@G_lin_2017

NA

@soong1992reproductive

@Madin_2016

@2020abc

@2020abcd

@2019

@Hoving_2015

@et/47509

@Timm_2020

NA

NA

@wourms1991reproduction

@wourms1991reproduction

@wourms1991reproduction

@wourms1991reproduction

@wourms1991reproduction

@wourms1991reproduction

@Moran_2007

@Gould_2016

@fishbase2000

NA

NA

@Madin_2016

@Bartilotti_2019

@2018a

@2018a

@Hoving_2015

@2014a

@Bushnell_2010

NA

NA

# ReturnToSpawningGround 


NA

@choat2012spawning

@Madin_2016

@Madin_2016

@Madin_2016

@Madin_2016

@Madin_2016

NA

NA

@Clucas_2018

@2014

@2018

NA

NA

@hoff2016identification

NA

NA

NA

NA

NA

NA

NA

NA

NA

@2020a

NA

NA

NA

@planque2016projecting

@Gonz_lez_Irusta_2015

@Madin_2016

NA

@2016

NA

NA

NA

@ongevity

@2007

NA

@fishbase2000

@Madin_2016

NA

NA

@Madin_2016

NA

@Madin_2016

@McIntyre_2020

NA

@fishbase2000

@fishbase2000

@Timm_2021

@2020ab

@Hohn_1996

NA

NA

@fishbase2000

@Madin_2016

NA

@Madin_2016

@Madin_2016

@Clucas_2018

@Clucas_2018

@Clucas_2018

NA

NA

NA

NA

@Brunel_2017

NA

NA

NA

NA

@Takano_1991

@Takano_1991

NA

NA

@Driggers_2014

NA

NA

@Madin_2016

NA

@LEE_2008

@ed_murre

NA

@2014a

NA

NA

NA

# Spawning_mode 


@Timm_2020

@cowen1997relationships

@Miller_2020

@Miller_2020

@Miller_2020

@Morse_1988

@Morse_1988

@cowen1997relationships

@Sebens_1981

NA

NA

NA

@O_Reilly_2018

@cowen1997relationships

@dulvy1997evolutionary

@dulvy1997evolutionary

@jivoff1998effect

@Moran_1997

@nelson2016fishes

@Arkhipkin_1996

@cowen1997relationships

@cowen1997relationships

@Chang_2018

@cowen1997relationships

NA

@Grigor_2017

@Schlesinger_2010

@cowen1997relationships

@Churchill_2016

@ye2023lunar

@Nakajima_2016

@moreinfo

NA

@cowen1997relationships

@Moore_2020

@cowen1997relationships

NA

@Lonard_2020

@10.5657/KFAS.2004.37.6.478

@fishbase2000

@Goffredo_2005

@cowen1997relationships

@cowen1997relationships

@Padilla_Gami_o_2012

@hanlon1998

@Davies_2017

@Barber_2016

@Carreras_2019

@cowen1997relationships

@leis1991pelagic

@Timm_2021

NA

NA

@grahame1989reproduction

@Frick_2004

@leis1991pelagic

@G_lin_2017

@cowen1997relationships

@smith1948atlantic

@2021coral

NA

NA

NA

@era.html

@et/47509

@Timm_2020

@Kerrison_2015

@fishbase2000

@wourms1991reproduction

@wourms1991reproduction

@wourms1991reproduction

@wourms1991reproduction

@wourms1991reproduction

@wourms1991reproduction

@Moran_2007

@Gould_2016

@fishbase2000

@cowen1997relationships

@cowen1997relationships

@vermeij2010release

@Bartilotti_2019

NA

NA

@ernalis

NA

@cowen1997relationships

@cowen1997relationships

@nelson2016fishes

# Larval_feeding 


@foxton1964observations

@cowen1997relationships

@Graham_2013

@Graham_2013

@Graham_2013

@Graham_2013

@Graham_2013

@cowen1997relationships

@Cornwell_2020

@Kooyman_1996

@2014

@2018

@Wolfowicz_2016

@cowen1997relationships

@dulvy1997evolutionary

@dulvy1997evolutionary

@Macedo_2019

@Moran_1997

@haber1986rare

@Arkhipkin_1996

@cowen1997relationships

@cowen1997relationships

NA

@cowen1997relationships

@2020a

@Grigor_2017

@45167

@cowen1997relationships

@Churchill_2016

@ye2023lunara

@Marquis_2005

@moreinfo

@2016

@cowen1997relationships

@Annis_2007

@cowen1997relationships

@ongevity

@2007

@10.5657/KFAS.2004.37.6.478

@fishbase2000

@Cairns_1999

@cowen1997relationships

@cowen1997relationships

@Baird_2009

@Villanueva_2016

@Baird_2009

@Hettinger_2013

@Fenaux_1985

@cowen1997relationships

@leis1991pelagic

@Timm_2021

@2020ab

@Hohn_1996

@vonvaupelklein1988strathmann

@Pfaller_2019

@leis1991pelagic

@Baird_2009

@cowen1997relationships

@Baird_2009

@Baird_2009

@Kooyman_1996

@Kooyman_1996

@Kooyman_1996

@Moreno_2008

@Guerra_Castro_2021

@Timm_2020

@Baweja_2016

@fishbase2000

@wourms1991reproduction

@wourms1991reproduction

@wourms1991reproduction

@wourms1991reproduction

@wourms1991reproduction

@wourms1991reproduction

@Moran_2007

@Gould_2016

@fishbase2000

@cowen1997relationships

@cowen1997relationships

@Baird_2009

@Bartilotti_2019

@LEE_2008

@ed_murre

@ernalis

@2014a

@cowen1997relationships

@cowen1997relationships

@nelson2016fishes

# isPlanktonic_atanypoint 


@Timm_2020

@cowen1997relationships

@Miller_2020

@Miller_2020

@Miller_2020

@Morse_1988

@Morse_1988

@cowen1997relationships

@Cornwell_2020

NA

NA

NA

@O_Reilly_2018

@cowen1997relationships

@dulvy1997evolutionary

@dulvy1997evolutionary

NA

@Moran_1997

@haber1986rare

@Arkhipkin_1996

@cowen1997relationships

@cowen1997relationships

@Chang_2018

@cowen1997relationships

NA

@Kosobokova_2017

@Bucher_2016

@cowen1997relationships

@Churchill_2016

@ye2023lunarab

@Babcock_1986

@moreinfo

NA

@cowen1997relationships

@Annis_2007

@cowen1997relationships

NA

@2007

@10.5657/KFAS.2004.37.6.478

@fishbase2000

@Goffredo_2005

@cowen1997relationships

@cowen1997relationships

@Padilla_Gami_o_2012

@Villanueva_2016

@Limer_2020

@Grossman_2020

@Carreras_2019

@cowen1997relationships

@leis1991pelagic

@Timm_2021

NA

NA

@vonvaupelklein1988strathmann

@Pfaller_2019

@leis1991pelagic

@Vandermeulen_1975

@cowen1997relationships

@smith1948atlantica

@2021corala

NA

NA

NA

@era.html

NA

@Timm_2020

NA

@Austin_1977

@Wourms_1991

@Wourms_1991

@Wourms_1991

@Wourms_1991

@Wourms_1991

@Takano_1991

@Moran_2007

@Gould_2016

@fishbase2000

@cowen1997relationships

@cowen1997relationships

@pta.html

@Bartilotti_2019

NA

NA

NA

NA

@cowen1997relationships

@cowen1997relationships

@nelson2016fishes

# isBenthic 


# PLD_point 


@Timm_2020

@wilson1999microstructure

@Miller_2020

@Miller_2020

@Miller_2020

@Morse_1988

@Morse_1988

@Nanninga_2015

@Cornwell_2020

NA

NA

NA

NA

NA

NA

NA

NA

@Moran_1997

NA

@Arkhipkin_1996

@Macpherson_2006

@Thresher_1989

@Chang_2018

@palomera1988larval

NA

@ata.html

@Bucher_2016

NA

NA

@campana1996year

@suwa2018precise

NA

NA

@Thresher_1985

@Annis_2007

@N__2001

NA

NA

@10.5657/KFAS.2004.37.6.478

@sea_bass

@ail/1285

@Puritz_2016

@Puritz_2016

@Alexander_2022

@Williams_2015

@Davies_2017

@Grossman_2020

@lpez1998larval

@reakakudla1985ecology

@Oshima_2010

@Timm_2021

NA

NA

NA

@Pfaller_2016

@Primo_2021

@Cumbo_2013

@reakakudla1985ecologya

@P__2001

@Storlazzi_2017

NA

NA

NA

@Timm_2020a

NA

@Timm_2020

@rafting2009

@villamor2004models

@coad2003rockfishes

@coad2003rockfishes

@coad2003rockfishes

@coad2003rockfishes

@coad2003rockfishes

@coad2003rockfishes

@Moran_2007

@Gould_2019

NA

@wellington1989planktonic

@wilson1999microstructure

NA

@Bartilotti_2019

NA

NA

@stephens1976statocyst, @pickford1961vertical

NA

@Callan_2018

@Wilson_1999

@nelson2016fishes

# Body_Size 


@sudnik2015maturation

@grim1989vestibuliferan

@Agudo_Adriani_2016

@Zubillaga_2007

@rn_coral

@Voss_2006

@a_undata

@fishbase2000

@Cornwell_2020

@Kooyman_1996

@2014

@2018

@annulata

@Thia_2021

@https://doi.org/10.1594/pangaea.900866

@https://doi.org/10.1594/pangaea.900866

@lue-Crab

@nebralis

@haber1986rare

@nchiidae

@Jansson_2020

@fishbase2000

@a_larynx

@https://doi.org/10.1594/pangaea.900866

@2020a

@ata.html

@aiptasia

@fishbase2000

@https://doi.org/10.1594/pangaea.900866

@fishbase2000

@veron1992hermatypic

@fishbase2000

@2016

@fishbase2000

@_lobster

@fishbase2000

@ongevity

@Estrada_2008

@Lim_2010

@fishbase2000

@Goffredo_2005a, @Caroselli_2012

@fishbase2000

@fishbase2000

@Nishikawa_2008

@nautilus

@bak1998coral

@zu_Ermgassen_2013

@Boudouresque_2013

@fishbase2000

@https://doi.org/10.1594/pangaea.900866

@20range

@2020ab

@Brownell_1987

@chraceus

@_minutus

@https://doi.org/10.1594/pangaea.900866

@richmond1987energetics

@fishbase2000

@Brandt_2009

@sudek2012histological

@Kooyman_1996

@Kooyman_1996

@Kooyman_1996

@flock1992species

@a_mangle

@1

@20years.

@https://doi.org/10.1594/pangaea.900866

@Vaux_2019

@https://doi.org/10.1594/pangaea.900866

@https://doi.org/10.1594/pangaea.900866

@https://doi.org/10.1594/pangaea.900866

@https://doi.org/10.1594/pangaea.900866

@Baeck_2012

@fishbase2000

@Gould_2016

@https://doi.org/10.1594/pangaea.900866

@fishbase2000

@fishbase2000

@Brandt_2009

@Griffiths_1983

@on_murre

@2018a

@Hoving_2015, @Golikov_2019

@2014a

@fishbase2000

@fishbase2000

@fishbase2000

# Fecundity_EggSize 

@timm2020comparativea, @sudnik2015maturationab

@Callan_2018

@Foster_2020

@Foster_2020

@Foster_2020

@Morse_1988

@Morse_1988

@X026.pdf

@sebens1980regulationa

@Kooyman_1996

NA

@2018

@Jennison_1981

@iss727

@https://doi.org/10.1594/pangaea.900866

@https://doi.org/10.1594/pangaea.900866

@Graham_2012

@Moran_1997

@haber1986rare

NA

@https://doi.org/10.1594/pangaea.900866

@Emel_yanova_2009

NA

@https://doi.org/10.1594/pangaea.900866

@2020a

NA

@Bucher_2016

NA

@https://doi.org/10.1594/pangaea.900866

@fishbase2000

@Okubo_2013

NA

@2016

NA

@Ouellet_2004

NA

@ongevity

NA

@10.5657/KFAS.2004.37.6.478

@kang2012early

@Cairns_1999

@Kasimatis_2015

@early2011

@haber1986rare

@https://doi.org/10.5061/dryad.k84c3k8j

@Holstein_2015

@haber1986rare

@Vafidis_2019

NA

@https://doi.org/10.1594/pangaea.900866

@Velazquez_2000

@2020ab

@Hohn_1996

@vonvaupelklein1988strathmann

NA

@https://doi.org/10.1594/pangaea.900866

@stoddart1985cycles

@Leu_2009



@2021coralab

@Kooyman_1996

@Kooyman_1996

@Kooyman_1996

@rolampas

@man.html

NA

NA

@https://doi.org/10.1594/pangaea.900866

@viviparous2023

@viviparous2023

@viviparous2023

@viviparous2023

@viviparous2023

@viviparous2023

@Moran_2007

@Gould_2016

@viviparous2023

NA

NA

@Lueg_2012

@Bartilotti_2019

@on_murre

@ed_murre

@ernalis

@2014a

@bushnell2010lunar

@Pavlov_2008

@polidoro2016list

